spring:
  application:
    name: shiro-ai
  datasource:
    url: jdbc:mysql://${datasource.ip}:${datasource.port}/shiro-ai?useUnicode=true&allowPublicKeyRetrieval=TRUE&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: shanghai
  ai:
    openai:
      base-url: ${ai.openai.base-url}
      api-key: ${ai.openai.api-key}
server:
  port: 3950

