spring:
  ai:
    openai:
      api-key: ${ai.openai.api-key}
      base-url: ${ai.openai.base-url}
      chat:
        options:
          model: ${ai.openai.default-deepseek-model}
          temperature: 0.7
  application:
    name: shiro-ai
  datasource:
    url: jdbc:mysql://${datasource.ip}:${datasource.port}/shiro-ai?useUnicode=true&allowPublicKeyRetrieval=TRUE&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: shanghai
  cloud:
    nacos:
      server-addr: ${nacos.server-addr}

server:
  port: 3950
logging:
  charset:
    file: UTF-8
  level:
    com.alice.shiroai: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"